# Generated by Django 4.0.2 on 2022-02-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-contact_date',), 'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries Submitted'},
        ),
    ]
