# Generated by Django 4.0.2 on 2022-02-11 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('contact_num', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='uploads/cvs/')),
                ('message', models.TextField(blank=True, null=True)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicant List',
                'ordering': ('-contact_date',),
            },
        ),
    ]
