# Generated by Django 4.0.2 on 2022-02-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_applicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ('-contact_date',), 'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-contact_date',), 'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
