# Generated by Django 4.0.2 on 2022-02-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_alter_job_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-updated',), 'verbose_name': 'job', 'verbose_name_plural': 'job Opportunities'},
        ),
    ]
