# Generated by Django 4.0.2 on 2022-02-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_category', '0002_alter_category_options'),
        ('jobs', '0006_jobcategory_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_category.category'),
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
