# Generated by Django 4.0.2 on 2022-02-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobcategory_alter_job_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-updated',), 'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'Categories'},
        ),
    ]
