# Generated by Django 4.0.2 on 2022-03-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_tags_alter_news_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-publish',), 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
