# Generated by Django 4.0.2 on 2022-02-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
