# Generated by Django 4.0.2 on 2022-02-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', models.TextField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'component',
                'verbose_name_plural': 'Components',
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('title',), 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
    ]
