# Generated by Django 4.0.2 on 2022-02-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_components_alter_page_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='components',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
