# Generated by Django 4.0.2 on 2022-02-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_components_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='body',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
