# Generated by Django 4.0.2 on 2022-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_body_components_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='heroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('banner_text', models.TextField(blank=True)),
                ('banner_cta_name', models.CharField(blank=True, max_length=250)),
                ('banner_cta_url', models.CharField(blank=True, max_length=250)),
                ('banner_image_desktop', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('banner_image_mobile', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'component',
                'verbose_name_plural': 'Components',
                'ordering': ('title',),
            },
        ),
    ]
