# Generated by Django 4.0.2 on 2022-02-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_assets_alter_herobanner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
