# Generated by Django 4.0.2 on 2022-02-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'job Categories'},
        ),
    ]
