# Generated by Django 4.0.2 on 2022-02-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
