# Generated by Django 4.0.2 on 2022-02-09 01:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('designation', models.CharField(blank=True, max_length=250)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('order_by', models.IntegerField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ('-created',),
            },
        ),
    ]
