# Generated by Django 4.0.2 on 2022-02-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='slug',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
