# Generated by Django 4.0.2 on 2022-02-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('-created',), 'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
