# Generated by Django 4.0.2 on 2022-03-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_alter_testimonial_options_alter_testimonial_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
