# Generated by Django 4.0.2 on 2022-03-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_alter_testimonial_options_alter_testimonial_order_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('order_by', 'status'), 'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
    ]
